# Generated by Django 3.1.7 on 2021-09-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msgid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=300)),
                ('email', models.CharField(default='', max_length=300)),
                ('phone', models.CharField(default='', max_length=300)),
                ('desc', models.CharField(default='', max_length=300)),
            ],
        ),
    ]
