# Generated by Django 3.1.7 on 2021-09-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('book_file', models.FileField(upload_to='Material/')),
                ('book_price', models.CharField(max_length=200)),
            ],
        ),
    ]
