# Generated by Django 3.1.7 on 2021-10-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20210925_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_books',
            name='id',
        ),
        migrations.AddField(
            model_name='upload_books',
            name='book_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
