# Generated by Django 3.1.7 on 2021-10-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20211014_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload_books',
            name='book_id',
        ),
        migrations.AddField(
            model_name='upload_books',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
