# Generated by Django 3.1.7 on 2021-10-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20211021_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_books',
            name='book_file',
            field=models.FileField(default='', upload_to='Material/'),
        ),
    ]
